# Generated by Django 5.2.9 on 2026-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('original_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('cs', 'Computer Science'), ('engineering', 'Engineering'), ('textbooks', 'Textbooks'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('content_summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
